#!/bin/bash

if ! [ "$#" -ge "1" ]
then
	>&2 echo "usage: $0 parameter-name"
	exit 1
fi

source $HOME/.bashrc
module load anaconda/2.3.0
source activate TimClusterPython3


ntasks=50
var="$1"

jobname="TSM-Bifurcation-$var"
output="$jobname-%j.out"
error="$jobname-%j.err"
## output="$jobname-%j-%t.out"
## error="$jobname-%j-%t.err"

export I_MPI_PMI_LIBRARY=/p/system/slurm/lib/libpmi.so
mysrun --qos=short --time=0-6 --job-name="$jobname" --output="$output" --error="$error" --ntasks=$ntasks --cpus-per-task=3 bifurcation_single "$var" &

